//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegisteration.StudentService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/StudentService")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudGenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StudIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudGender {
            get {
                return this.StudGenderField;
            }
            set {
                if ((object.ReferenceEquals(this.StudGenderField, value) != true)) {
                    this.StudGenderField = value;
                    this.RaisePropertyChanged("StudGender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudID {
            get {
                return this.StudIDField;
            }
            set {
                if ((this.StudIDField.Equals(value) != true)) {
                    this.StudIDField = value;
                    this.RaisePropertyChanged("StudID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudName {
            get {
                return this.StudNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StudNameField, value) != true)) {
                    this.StudNameField = value;
                    this.RaisePropertyChanged("StudName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StudentService.IStudentService")]
    public interface IStudentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/insertData", ReplyAction="http://tempuri.org/IStudentService/insertDataResponse")]
        int insertData(StudentRegisteration.StudentService.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/insertData", ReplyAction="http://tempuri.org/IStudentService/insertDataResponse")]
        System.Threading.Tasks.Task<int> insertDataAsync(StudentRegisteration.StudentService.Student student);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStudentServiceChannel : StudentRegisteration.StudentService.IStudentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentServiceClient : System.ServiceModel.ClientBase<StudentRegisteration.StudentService.IStudentService>, StudentRegisteration.StudentService.IStudentService {
        
        public StudentServiceClient() {
        }
        
        public StudentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int insertData(StudentRegisteration.StudentService.Student student) {
            return base.Channel.insertData(student);
        }
        
        public System.Threading.Tasks.Task<int> insertDataAsync(StudentRegisteration.StudentService.Student student) {
            return base.Channel.insertDataAsync(student);
        }
    }
}
